default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: mikasa_development
test:
  <<: *default
  database: mikasa_test
production:
  <<: *default
  host: <%= ENV['MIKASA_DATABASE_HOST'] %>
  database: mikasa_production
  username: <%= ENV['MIKASA_DATABASE_USERNAME'] %>
  password: <%= ENV['MIKASA_DATABASE_PASSWORD'] %>
